name: character_search_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  bloc_concurrency: ^0.2.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  mocktail: ^1.0.0
  provider: ^6.0.5
  retrofit: ^4.0.1
  watcher: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flavorDimensions: "app"
productFlavors:
  variant1:
    name: "Variant 1"
    package: "com.example.app.variant1"
    flavorUrl: "http://api.duckduckgo.com/?q=simpsons+characters&format=json"
  variant2:
    name: "Variant 2"
    package: "com.example.app.variant2"
    flavorUrl: "http://api.duckduckgo.com/?q=the+wire+characters&format=json"
